### ISSUE TITLE
Manual needed

### ISSUE THREAD

**Issue by paris0120** [andredumas/techan.js#71] opened 2015-06-10 12:06 UTC
Hi,

I'm wondering if you have any manuals for this awesome software. I'm looking for how to add my own data on the chart (the indicators I calculated). Also if you can write a tuition about how to write a indicator for techan, i think the others and I can contribute too. I tried to pull from your repo but it looks like that the repo misses ../build/version or something else. Anyway the source file doesn't work. 

I'm new to javascript and git. I just need it for a project. forgive me if I have any mistakes.

**Comment by andredumas** [comment] 2015-08-10 03:07
Hi @paris0120 

Unfortunately no manuals at the moment. I will add an example of a bare indicator as there has been a few questions about this in the past. Fundamentally it's all d3, so adding an indicator _should_ be as straight forward as standard d3 manipulation. There are a few other concepts/conventions I also follow for slight optimisations here and there, but ultimately it's d3. I was also thinking of a separate `techan.js-extensions`which would be an area where optional extras would be added.

BTW version is a generated file. `npm test` or `npm start`, which I normally execute during development, is enough to get it generated.

andre

**Comment by andredumas** [comment] 2015-11-08 09:00
Duplicate of #1

**Closed by andredumas** 2015-11-08 09:00 UTC
Labels: duplicate
